language: node_js
node_js:
- node
- '7'
- '6'
- '4'
install: npm install
before_install:
- if [[ `npm -v` = 2* ]]; then npm i -g npm@3; fi
- echo "//registry.npmjs.org/:_authToken=\${NPM_KEY}" > ~/.npmrc
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success: ".travis/ci-release.jsh"
env:
  global:
  - secure: Y6WEQq4SL9E5K1beJ9JNgAw/bsxYyMDfEId7aj0IHE3M1XDoXrC6EQVjg5ARuDcPntPX1Vowj9VVh68dleVy5bI4Xc0KtXe/PDCEH7yccgLDHnSpIQR7yJNOYkKpyetcNOJkQwKVDpvt2OpjKFC9GJNeMv4EW5w5CuxcxSref8yMBsMv2vYcDIDlkxUtshpXx3vSL0fSWSIoQTHKMw5Id3Sc9lysxD+Gg+feWrKODaR0ZFZY9BEN2ZFN/EFfJhHx3wZTRcBK3cOnJZSoYdwrRo/I3cXhXG+QmiNx2nG+AZBX5qRMzehZRoZggc1doA6bSObjrMRa+Fvv1vZBiYIbZkQcnAmRpdhOfDTVYeKhrFN8k9Jo9w8BeD3ape01V+E/+8vtVWHTfAIwrj4qgitHKdJ+Sgzx9Up0BtXqltZbedq2MiFffhTt0vgsZDkPLClHqZ2DZgF4o2h2ihE/gJhI+BcSkxJ/k1BroWi/DI8qKHb3LiQbQljoT53xMDJF1FiyTOIcbk4be2AiCKlUxn8p9oczyLSjhU2wlKV6ZzbCbaXfgc8jhZo1B8uaSGjFe1mAWo6P1N2654YBMGzV35/aaaMFksjSxeXN0+H6mRQK7uo7WkaGA+iwtUPeZu8h7FeuCGkz1UEXDRtYvEXQfwZ3TI/gIn/52wxHz2Grp8LJK04=
  - secure: BaRE2pNfb1d/YsEonFM4DtHkKjZdDDQIlz5lXN4/rvpBm6FC0zYETLRakn3zkux6wFH2dBOvHFeNig3T2ALyYD35Umhv3LzxRNnxknkkFUkumzLs2j1YYyNNEHsDwP8WrG059NP0tGspiSYSlcIbxyT/MIrdYQs2IBSer2SjXx7JWPuBLjiErxbCpBG9ax7+SilGqoba4xAtpToKq8EifOip7D59RwQvc9+u3R5qMIpDaZgJqFqeL6nntcM/rQqlV4o/P0BRrLjMUEGs1j08LDn3Hm29uWhP8EPzPee6vBcDtDkZCQgfzH+cfWU+qASV3DxqR+MylnKQHb0NB74hlhx1NFbq39pQ0zulG20my+LykRPjDSoYS43nLuXIibXXTXo8zYhCcrRnFzy2jKYyI/dnIJK75GBr7y9fciFJXbh2VcR3crUbCV0BgA8V4utZlw447fVIWDNuEhQiXkFqE8M67Z6Nx/qj9H74gQEtbUVhCLCubFr8NNnvKomOhl5Mpc6O/Hop0r7Jyif9B05h4LYsvtpoQDsk95TxnBiTtgmK+lmJYdet0WNLm89n/5T6R/Rbo6TlAKy96oSk3js3hs8lD0L2hxcOdl4Pv/bzl9S3733oZuSkkv4HWA1JlqKvNBJDdujqSJu4x+LFR2Wpa1NO07KId4hQAPslERYAytY=
